In [71]:
import pandas as pd

In [73]:
data= pd.read_csv(r'loan_approval_dataset.csv')

In [77]:
data

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,4265,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,4266,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,4267,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,4268,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,4269,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [79]:
data.drop(columns=['loan_id'], inplace=True)

In [81]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected
...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected
4265,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved
4266,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected
4267,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved
4268,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved

In [83]:
data.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [85]:
data.columns=data.columns.str.strip()

In [87]:
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [89]:
data['Assets']=data.residential_assets_value + data.commercial_assets_value + data.luxury_assets_value + data.bank_asset_value

In [91]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status,Assets
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected,17000000
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected,57700000
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected,55000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4264,5,Graduate,Yes,1000000,2300000,12,317,2800000,500000,3300000,800000,Rejected,7400000
4265,0,Not Graduate,Yes,3300000,11300000,20,559,4200000,2900000,11000000,1900000,Approved,20000000
4266,2,Not Graduate,No,6500000,23900000,18,457,1200000,12400000,18100000,7300000,Rejected,39000000
4267,1,Not Graduate,No,4100000,12800000,8,780,8200000,700000,14100000,5800000,Approved,28800000
4268,1,Graduate,No,9200000,29700000,10,607,17800000,11800000,35700000,12000000,Approved,77300000

In [93]:
data.drop(columns=['residential_assets_value','commercial_assets_value', 'luxury_assets_value', 'bank_asset_value'], inplace=True)

In [63]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,0,9600000,29900000,12,778,0,50700000
1,0,0,1,4100000,12200000,8,417,1,17000000
2,3,1,0,9100000,29700000,20,506,1,57700000
3,3,1,0,8200000,30700000,8,467,1,52700000
4,5,0,1,9800000,24200000,20,382,1,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,1,7400000
4265,0,0,1,3300000,11300000,20,559,0,20000000
4266,2,0,0,6500000,23900000,18,457,1,39000000
4267,1,0,0,4100000,12800000,8,780,0,28800000
4268,1,1,0,9200000,29700000,10,607,0,77300000

In [97]:
data.isnull().sum()

no_of_dependents    0
education           0
self_employed       0
income_annum        0
loan_amount         0
loan_term           0
cibil_score         0
loan_status         0
Assets              0
dtype: int64

In [35]:
##To view distinct value in the column

In [99]:
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'loan_status', 'Assets'],
      dtype='object')

In [101]:
data.education.unique()

array([' Graduate', ' Not Graduate'], dtype=object)

In [103]:
#To remove extra spcae before the enire column

In [105]:
def clean_data (st):
    st= st. strip()
    return (st)

In [107]:
clean_data(' Graduate')

'Graduate'

In [109]:
## To apply this to enire column

In [111]:
data.education = data.education.apply(clean_data)

In [113]:
data.education.unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [115]:
data['education']=data['education'].replace(['Graduate', 'Not Graduate'],[1,0])

C:\Users\deepa\AppData\Local\Temp\ipykernel_9676\3404062094.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['education']=data['education'].replace(['Graduate', 'Not Graduate'],[1,0])

In [117]:
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'loan_status', 'Assets'],
      dtype='object')

In [119]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,No,9600000,29900000,12,778,Approved,50700000
1,0,0,Yes,4100000,12200000,8,417,Rejected,17000000
2,3,1,No,9100000,29700000,20,506,Rejected,57700000
3,3,1,No,8200000,30700000,8,467,Rejected,52700000
4,5,0,Yes,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,Yes,1000000,2300000,12,317,Rejected,7400000
4265,0,0,Yes,3300000,11300000,20,559,Approved,20000000
4266,2,0,No,6500000,23900000,18,457,Rejected,39000000
4267,1,0,No,4100000,12800000,8,780,Approved,28800000
4268,1,1,No,9200000,29700000,10,607,Approved,77300000

In [121]:
data.self_employed.unique()

array([' No', ' Yes'], dtype=object)

In [123]:
data.self_employed = data.self_employed.apply(clean_data)

In [125]:
data.self_employed.unique()

array(['No', 'Yes'], dtype=object)

In [127]:
data['self_employed'] = data['self_employed'].replace(['No', 'Yes'],[0,1])

C:\Users\deepa\AppData\Local\Temp\ipykernel_9676\2517122703.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['self_employed'] = data['self_employed'].replace(['No', 'Yes'],[0,1])

In [129]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,0,9600000,29900000,12,778,Approved,50700000
1,0,0,1,4100000,12200000,8,417,Rejected,17000000
2,3,1,0,9100000,29700000,20,506,Rejected,57700000
3,3,1,0,8200000,30700000,8,467,Rejected,52700000
4,5,0,1,9800000,24200000,20,382,Rejected,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,Rejected,7400000
4265,0,0,1,3300000,11300000,20,559,Approved,20000000
4266,2,0,0,6500000,23900000,18,457,Rejected,39000000
4267,1,0,0,4100000,12800000,8,780,Approved,28800000
4268,1,1,0,9200000,29700000,10,607,Approved,77300000

In [131]:
data.loan_status.unique()

array([' Approved', ' Rejected'], dtype=object)

In [133]:
data.loan_status = data.loan_status.apply(clean_data)

In [135]:
data.loan_status.unique()

array(['Approved', 'Rejected'], dtype=object)

In [137]:
data['loan_status']= data['loan_status'].replace(['Approved', 'Rejected'],[0,1])

C:\Users\deepa\AppData\Local\Temp\ipykernel_9676\900592411.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['loan_status']= data['loan_status'].replace(['Approved', 'Rejected'],[0,1])

In [139]:
data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,loan_status,Assets
0,2,1,0,9600000,29900000,12,778,0,50700000
1,0,0,1,4100000,12200000,8,417,1,17000000
2,3,1,0,9100000,29700000,20,506,1,57700000
3,3,1,0,8200000,30700000,8,467,1,52700000
4,5,0,1,9800000,24200000,20,382,1,55000000
...,...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,1,7400000
4265,0,0,1,3300000,11300000,20,559,0,20000000
4266,2,0,0,6500000,23900000,18,457,1,39000000
4267,1,0,0,4100000,12800000,8,780,0,28800000
4268,1,1,0,9200000,29700000,10,607,0,77300000

In [141]:
##To select model

In [143]:
from sklearn.model_selection import train_test_split

In [147]:
input_data=data.drop(columns=['loan_status'])
output_data = data['loan_status']

In [149]:
input_data

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,Assets
0,2,1,0,9600000,29900000,12,778,50700000
1,0,0,1,4100000,12200000,8,417,17000000
2,3,1,0,9100000,29700000,20,506,57700000
3,3,1,0,8200000,30700000,8,467,52700000
4,5,0,1,9800000,24200000,20,382,55000000
...,...,...,...,...,...,...,...,...
4264,5,1,1,1000000,2300000,12,317,7400000
4265,0,0,1,3300000,11300000,20,559,20000000
4266,2,0,0,6500000,23900000,18,457,39000000
4267,1,0,0,4100000,12800000,8,780,28800000
4268,1,1,0,9200000,29700000,10,607,77300000

In [ ]:
## To split the data using train_test_split

In [153]:
x_train,x_test,y_train,y_test = train_test_split(input_data, output_data, test_size=0.2)

In [151]:
output_data

0       0
1       1
2       1
3       1
4       1
       ..
4264    1
4265    0
4266    1
4267    0
4268    0
Name: loan_status, Length: 4269, dtype: int64

In [155]:
x_train.shape,x_test.shape, y_train.shape, y_test.shape

((3415, 8), (854, 8), (3415,), (854,))

In [157]:
## To improve the performance of the data we are scaling the data using standard scaler

In [159]:
from sklearn.preprocessing import StandardScaler

In [161]:
scaler= StandardScaler()

In [163]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [165]:
## To create our model

In [171]:
from sklearn.linear_model import LogisticRegression

In [175]:
model=LogisticRegression()

In [177]:
model.fit(x_train_scaled, y_train)

LogisticRegression()

In [181]:
model.score(x_test_scaled,y_test)

0.9309133489461359

In [183]:
## To Predict some values

In [185]:
pred_data= pd.DataFrame([['5','0','1','9800000','24200000','20','382','55000000']],columns=['no_of_dependents','education','self_employed','income_annum','loan_amount','loan_term','cibil_score','Assets'])

In [187]:
pred_data= scaler.transform(pred_data)

In [189]:
model.predict(pred_data)

array([1], dtype=int64)

In [191]:
import pickle as pk

In [193]:
pk.dump(model, open('model.pkl','wb'))

In [195]:
pk.dump(scaler, open('scaler.pkl','wb'))